### ISSUE TITLE
Can't erase canvas with empty (transparent) canvas

### ISSUE THREAD

**Issue by HJerem** [Korilakkuma/CanvasView#4]
I can't erase canvas with `PorterDuffXfermode(PorterDuff.Mode.CLEAR)`
Do you know if it's possible ?

**Comment by HJerem** [comment]
I found a solution, the only way is to clear the list of paths and to redraw.

**Comment by Korilakkuma** [comment]
Thank you.

**Comment by HJerem** [comment]
In fact, I need to have an erase tool. How do I do that ?

**Comment by alexliubj** [comment]
@HJerem  How did you finally make it?
Did you draw a transparent path as an erase.

**Comment by aerdy** [comment]
@HJerem Add method getBitmap transparance here:

 public Bitmap getBitmap() {
        this.setDrawingCacheEnabled(false);
        this.setDrawingCacheEnabled(true);
        bitmap = Bitmap.createBitmap(getWidth(), getHeight(), Bitmap.Config.ARGB_8888);
        bitmap.eraseColor(Color.TRANSPARENT);
        return Bitmap.createBitmap(this.getDrawingCache());
    }
